### PR TITLE
Bebop2

### PR DESCRIPTION
**Pull request by qijungu**

### CODE REVIEW

**Comment by n0es1s** [comment]
When will you have some Repos up at https://github.com/ARDroneSDK3 ? No SDK yet for controlling flight functions on Bebop 2??

**Comment by YoanBesson** [comment]
My bad, SDK address is wrong. Please use this one:
https://github.com/Parrot-Developers/arsdk_manifests

**Comment by n0es1s** [comment]
I actually found that a little later. Thanks for letting me know! Any
chance you guys will roll it out in python soon?? :)

Thanks again,

**Comment by n0es1s** [comment]
Why are you guys removing bebop2?

**Comment by ymorgan** [comment]
It has been moved here:
https://github.com/Parrot-Developers/bebop2-opensource

**Pull request closed without merging**
